#!/usr/bin/env python3
"""
dieckow_hamilton_fit.py — Hamilton ODE fitting to Dieckow 2025 microbiome data.

Pipeline:
  taxonomy TSVs → φ_obs(patient, week) → simulate_0d_nsp → TMCMC (GPU vmap)

Design: n_sp=5 shared-A
  - n_sp = 5 (same 5 genera as Szafranski cross-sectional → direct comparison)
  - Shared A matrix across all patients (15 params) — same ecology rules
  - Per-patient b vectors (10 patients × 5 = 50 params) — patient growth rates differ
  - Total: 65 params / 100 data = 1.54×

GPU acceleration:
  - jax.vmap over 10 patients inside log_likelihood (10× per-step speedup)
  - tmcmc_nuts_engine: jax.vmap over particles for batch GPU eval
  - Compile-time unrolled 2-week simulation (MAX_PRED=2)

Genera (fixed order, matches Szafranski GMM analysis):
  0: Streptococcus (So)
  1: Actinomyces   (An)
  2: Veillonella   (Vd)
  3: Fusobacterium (Fn)
  4: Porphyromonas (Pg)

Theta layout (65 params):
  theta[0:15]   — A upper triangle (shared)
  theta[15:20]  — b for patient A
  theta[20:25]  — b for patient B
  ...
  theta[60:65]  — b for patient L

Usage:
  # Build data matrix from taxonomy TSVs
  python dieckow_hamilton_fit.py --build-data

  # Fit (GPU, RW-TMCMC, 100 particles)
  CUDA_VISIBLE_DEVICES=1 python dieckow_hamilton_fit.py --fit --n-particles 100 --mutation rw

  # Inspect loaded data
  python dieckow_hamilton_fit.py --info
"""
import argparse
import json
import os
import sys
import collections
import numpy as np
import pandas as pd
from pathlib import Path

# ── Device selection BEFORE JAX import ──────────────────────────────────────
def _parse_device_early():
    for i, a in enumerate(sys.argv):
        if a == '--device' and i + 1 < len(sys.argv):
            return sys.argv[i + 1]
    return 'auto'

_dev = _parse_device_early()
if _dev == 'cpu':
    os.environ['CUDA_VISIBLE_DEVICES'] = ''
elif _dev in ('auto', 'gpu'):
    if 'JAX_PLATFORMS' not in os.environ:
        os.environ['JAX_PLATFORMS'] = 'cuda'
    try:
        import jax_cuda12_plugin  # noqa: F401
    except ImportError:
        pass

import jax
import jax.numpy as jnp
jax.config.update('jax_enable_x64', True)

sys.path.insert(0, '/home/nishioka/IKM_Hiwi/Tmcmc202601/data_5species/main')
sys.path.insert(0, '/home/nishioka/IKM_Hiwi/Tmcmc202601/data_5species/core')

try:
    from hamilton_ode_jax_nsp import simulate_0d_nsp, count_params, theta_to_matrices
    HAS_JAX = True
except ImportError:
    HAS_JAX = False
    print("WARNING: JAX not available — simulation will not run")

MANIFEST     = Path('/home/nishioka/IKM_Hiwi/nife/dieckow_manifest.tsv')
TAXONOMY_DIR = Path('/home/nishioka/IKM_Hiwi/nife/results/dieckow_taxonomy')
DATA_CACHE   = Path('/home/nishioka/IKM_Hiwi/nife/results/dieckow_obs_matrix_5sp.json')

# Fixed 5-genus order — matches Szafranski GMM analysis
N_SP         = 5
GENERA_5     = ['Streptococcus', 'Actinomyces', 'Veillonella', 'Fusobacterium', 'Porphyromonas']
PATIENT_ORDER = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'L']  # I, J absent

N_PATIENTS   = len(PATIENT_ORDER)
N_A_PARAMS   = N_SP * (N_SP + 1) // 2   # 15 — shared A upper triangle
N_B_PARAMS   = N_SP * N_PATIENTS         # 50 — per-patient b
N_PARAMS     = N_A_PARAMS + N_B_PARAMS   # 65

N_STEPS      = 2500    # ODE steps per week
DT           = 1e-4
C_CONST      = 25.0
ALPHA_CONST  = 100.0

# Metabolic sign constraints — auto-extracted from Neo4j (Dieckow SI + MOESM3)
# Upper triangle index: genera So=0, An=1, Vd=2, Fn=3, Pg=4
#   k = row*(2*N_SP - row - 1)//2 + col  for row<=col
#
# Generated by: query_neo4j_prior.py  (see results/neo4j_import/)
# σ=1.0 → experimental evidence  /  σ=2.0 → prediction only
#
# k=4 A[So,Pg]: CONFLICT — So→lactate→Pg(+) vs So→H2O2→Pg(-) → excluded from prior
#
# {upper_triangle_index: (expected_sign, sigma)}
_META_SIGN_PRIOR = {
    1: (+1, 1.0),   # A[So,An]: An→nitrite→So        (experimental, bidirectional)
    2: (+1, 1.0),   # A[So,Vd]: So→lactate→Vd + Vd→nitrite/CO2→So  (experimental, bidirectional)
    3: (+1, 1.0),   # A[So,Fn]: So→L-ornithine→Fn    (experimental)
    6: (+1, 1.0),   # A[An,Vd]: An→lactate→Vd        (experimental)
    8: (+1, 1.0),   # A[An,Pg]: An→lactate/menaquinone→Pg  (experimental) ※Pg pasteri 由来
   11: (+1, 1.0),   # A[Vd,Pg]: Vd→menaquinone→Pg    (experimental)
}


# ---------------------------------------------------------------------------
# Theta layout helpers
# ---------------------------------------------------------------------------

def extract_patient_theta(theta, patient_idx):
    """
    Joint theta (65) → single-patient theta (20) for simulate_0d_nsp.
    Layout: [A_utri(15), b_patient(5)]
    """
    A_utri = theta[:N_A_PARAMS]
    b_start = N_A_PARAMS + patient_idx * N_SP
    b = theta[b_start: b_start + N_SP]
    return np.concatenate([A_utri, b])


def patient_index(patient_id):
    return PATIENT_ORDER.index(patient_id)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def build_obs_matrix():
    """
    Load taxonomy TSVs → obs[patient] = np.array (5, 3)
    Column order: [So, An, Vd, Fn, Pg], rows: [week1, week2, week3] transposed.
    Returns: obs dict[patient_id → (5, 3) array]
    """
    manifest = pd.read_csv(MANIFEST, sep='\t')
    records = {}
    for _, row in manifest.iterrows():
        tsv = TAXONOMY_DIR / f"{row['sample']}_taxonomy.tsv"
        if not tsv.exists():
            continue
        df = pd.read_csv(tsv, sep='\t')
        total = df['count'].sum()
        counts = {g: c / total for g, c in zip(df['genus'], df['count'])}
        records[row['sample']] = counts

    missing = set(manifest['sample']) - set(records)
    if missing:
        print(f"WARNING: {len(missing)} samples not yet processed: {sorted(missing)}")

    obs = {}
    for _, row in manifest.iterrows():
        patient = row['patient']
        tp = int(row['timepoint']) - 1   # 0-indexed
        sample = row['sample']
        if sample not in records:
            continue
        if patient not in obs:
            obs[patient] = np.zeros((N_SP, 3))
        for k, genus in enumerate(GENERA_5):
            # sum all matching genus-level counts (substring match)
            val = sum(v for g, v in records[sample].items()
                      if genus.lower() in g.lower())
            obs[patient][k, tp] = val

    # Renormalize each timepoint
    for patient in obs:
        for t in range(3):
            s = obs[patient][:, t].sum()
            if s > 0:
                obs[patient][:, t] /= s

    return obs


def load_or_build_data(force=False):
    if not force and DATA_CACHE.exists():
        with open(DATA_CACHE) as f:
            d = json.load(f)
        obs = {p: np.array(v) for p, v in d['obs'].items()}
        print(f"Loaded cache: {len(obs)} patients, genera={GENERA_5}")
        return obs

    obs = build_obs_matrix()
    DATA_CACHE.parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_CACHE, 'w') as f:
        json.dump({'genera': GENERA_5, 'obs': {p: v.tolist() for p, v in obs.items()}}, f, indent=2)
    print(f"Saved cache: {DATA_CACHE}")
    return obs


# ---------------------------------------------------------------------------
# ODE forward model — JAX-pure (vmappable)
# ---------------------------------------------------------------------------

MAX_PRED = 2   # max prediction weeks per patient (compile-time constant)


def simulate_patient(theta_20, phi_init, n_weeks=2):
    """NumPy wrapper for single-patient simulation (used by rmse_joint/info)."""
    if not HAS_JAX:
        raise RuntimeError("JAX not available")
    theta_jax = jnp.array(theta_20, dtype=jnp.float64)
    phi_cur = jnp.array(phi_init, dtype=jnp.float64)
    preds = []
    for _ in range(n_weeks):
        traj = simulate_0d_nsp(
            theta_jax, n_sp=N_SP, n_steps=N_STEPS, dt=DT,
            phi_init=phi_cur, c_const=C_CONST, alpha_const=ALPHA_CONST,
        )
        pb = np.array(traj[-1])
        s = pb.sum()
        pb = pb / s if s > 0 else pb
        preds.append(pb)
        phi_cur = jnp.array(pb)
    return np.array(preds)


def _sim_2weeks_jax(theta_20, phi_init):
    """Pure JAX: run 2 consecutive ODE weeks, return (2, N_SP) phibar."""
    theta_64 = theta_20.astype(jnp.float64)
    phi_cur = phi_init.astype(jnp.float64)
    # Week 1
    traj1 = simulate_0d_nsp(theta_64, n_sp=N_SP, n_steps=N_STEPS, dt=DT,
                              phi_init=phi_cur, c_const=C_CONST, alpha_const=ALPHA_CONST)
    phi1 = traj1[-1]
    phi1 = phi1 / jnp.maximum(phi1.sum(), 1e-12)
    # Week 2
    traj2 = simulate_0d_nsp(theta_64, n_sp=N_SP, n_steps=N_STEPS, dt=DT,
                              phi_init=phi1, c_const=C_CONST, alpha_const=ALPHA_CONST)
    phi2 = traj2[-1]
    phi2 = phi2 / jnp.maximum(phi2.sum(), 1e-12)
    return jnp.stack([phi1, phi2])   # (2, N_SP)


def _log_lik_one_patient(theta_20, phi_init, obs_future, valid, sigma):
    """JAX pure: log-likelihood for one patient.
    theta_20: (20,), phi_init: (N_SP,),
    obs_future: (MAX_PRED, N_SP), valid: (MAX_PRED,) 0/1 mask.
    """
    preds = _sim_2weeks_jax(theta_20, phi_init)          # (2, N_SP)
    residuals = preds - obs_future                        # (2, N_SP)
    ll_per_week = -0.5 * jnp.sum((residuals / sigma)**2, axis=1)  # (2,)
    return jnp.sum(ll_per_week * valid)


# vmapped over patient axis — called with batched arrays
_log_lik_patients_vmap = jax.vmap(
    _log_lik_one_patient, in_axes=(0, 0, 0, 0, None)
)


def make_log_likelihood_joint_jax(obs, sigma=0.05):
    """Build a pure-JAX log_likelihood(theta) closure over the patient batch.

    Pre-computes phi_init_batch, obs_future_batch, valid_batch as JAX arrays.
    Inner vmap evaluates all N_PATIENTS in parallel on GPU.
    """
    phi_init_list, obs_future_list, valid_list = [], [], []

    for patient in PATIENT_ORDER:
        if patient not in obs:
            phi_init_list.append(np.ones(N_SP, dtype=np.float64) / N_SP)
            obs_future_list.append(np.zeros((MAX_PRED, N_SP), dtype=np.float64))
            valid_list.append(np.zeros(MAX_PRED, dtype=np.float64))
            continue
        phi_obs = obs[patient]                        # (N_SP, 3)
        weeks_ok = int((phi_obs.sum(axis=0) > 0).sum())

        phi0 = phi_obs[:, 0].astype(np.float64)
        phi0 = np.clip(phi0, 1e-6, 1.0)
        phi0 /= phi0.sum()
        phi_init_list.append(phi0)

        obs_f = np.zeros((MAX_PRED, N_SP), dtype=np.float64)
        valid = np.zeros(MAX_PRED, dtype=np.float64)
        n_pred = min(weeks_ok - 1, MAX_PRED)
        for t in range(n_pred):
            obs_f[t] = phi_obs[:, t + 1]
            valid[t] = 1.0
        obs_future_list.append(obs_f)
        valid_list.append(valid)

    # Static JAX arrays (captured by closure)
    phi_init_b  = jnp.array(np.array(phi_init_list),   dtype=jnp.float64)  # (P, N_SP)
    obs_future_b = jnp.array(np.array(obs_future_list), dtype=jnp.float64)  # (P, 2, N_SP)
    valid_b     = jnp.array(np.array(valid_list),       dtype=jnp.float64)  # (P, 2)
    sigma_jax   = jnp.float64(sigma)

    def log_likelihood(theta):
        """theta: (65,) → scalar log-likelihood (GPU vmap over 10 patients)."""
        theta64 = theta.astype(jnp.float64)
        A_utri  = theta64[:N_A_PARAMS]   # (15,)

        # Build (N_PATIENTS, 20) theta batch via vmap over patient indices
        def theta_for_patient(i):
            b_start = N_A_PARAMS + i * N_SP
            b_i = jax.lax.dynamic_slice(theta64, (b_start,), (N_SP,))
            return jnp.concatenate([A_utri, b_i])

        theta_batch = jax.vmap(theta_for_patient)(
            jnp.arange(N_PATIENTS, dtype=jnp.int32))      # (P, 20)

        ll_per_patient = _log_lik_patients_vmap(
            theta_batch, phi_init_b, obs_future_b, valid_b, sigma_jax)  # (P,)
        return jnp.sum(ll_per_patient)

    return log_likelihood


# ---------------------------------------------------------------------------
# Likelihood / prior (joint over all patients)
# ---------------------------------------------------------------------------

def log_likelihood_joint(theta, obs, sigma=0.05):
    """
    Sum log-likelihood over all patients.
    obs: dict[patient_id → (5, 3) array]
    """
    ll = 0.0
    for i, patient in enumerate(PATIENT_ORDER):
        if patient not in obs:
            continue
        phi_obs = obs[patient]
        weeks_ok = (phi_obs.sum(axis=0) > 0).sum()
        if weeks_ok < 2:
            continue
        theta_p = extract_patient_theta(theta, i)
        phi_init = phi_obs[:, 0]
        n_pred = weeks_ok - 1
        try:
            pred = simulate_patient(theta_p, phi_init, n_weeks=n_pred)
            obs_future = phi_obs[:, 1:1+n_pred].T
            residuals = pred - obs_future
            ll += -0.5 * np.sum((residuals / sigma) ** 2)
        except Exception:
            ll += -1e12
    return ll


def log_prior_joint(theta):
    """NumPy version — used only by legacy rmse_joint path."""
    A_utri = theta[:N_A_PARAMS]
    b_all  = theta[N_A_PARAMS:]
    if np.any(A_utri < -5) or np.any(A_utri > 5):
        return -np.inf
    if np.any(b_all < 0.01) or np.any(b_all > 15):
        return -np.inf
    lp = 0.0
    for k, (expected_sign, sigma) in _META_SIGN_PRIOR.items():
        v = A_utri[k]
        if expected_sign > 0 and v < 0:
            lp += -0.5 * (v / sigma) ** 2
        elif expected_sign < 0 and v > 0:
            lp += -0.5 * (v / sigma) ** 2
    return lp


def make_log_prior_jax():
    """Pure-JAX soft sign prior for tmcmc_nuts_engine (log_prior_fn arg)."""
    items = list(_META_SIGN_PRIOR.items())  # static at compile time

    def log_prior_fn(theta):
        A_utri = theta[:N_A_PARAMS].astype(jnp.float64)
        lp = jnp.float64(0.0)
        for k, (exp_sign, sig) in items:
            v = A_utri[k]
            if exp_sign > 0:
                lp = jnp.where(v < 0, lp - 0.5 * (v / sig) ** 2, lp)
            else:
                lp = jnp.where(v > 0, lp - 0.5 * (v / sig) ** 2, lp)
        return lp

    return log_prior_fn


def rmse_joint(theta, obs):
    total, n = 0.0, 0
    for i, patient in enumerate(PATIENT_ORDER):
        if patient not in obs:
            continue
        phi_obs = obs[patient]
        weeks_ok = (phi_obs.sum(axis=0) > 0).sum()
        if weeks_ok < 2:
            continue
        theta_p = extract_patient_theta(theta, i)
        phi_init = phi_obs[:, 0]
        n_pred = weeks_ok - 1
        pred = simulate_patient(theta_p, phi_init, n_weeks=n_pred)
        obs_future = phi_obs[:, 1:1+n_pred].T
        total += np.sum((pred - obs_future) ** 2)
        n += pred.size
    return float(np.sqrt(total / n)) if n > 0 else float('nan')


# ---------------------------------------------------------------------------
# TMCMC — GPU-accelerated via tmcmc_nuts_engine (vmap over particles)
# ---------------------------------------------------------------------------

def _make_prior_bounds():
    """Return [N_PARAMS, 2] prior bounds array for tmcmc_nuts_engine."""
    bounds = np.zeros((N_PARAMS, 2))
    bounds[:N_A_PARAMS]  = [-5.0, 5.0]    # A upper triangle
    bounds[N_A_PARAMS:]  = [0.01, 15.0]   # per-patient b
    return bounds


def run_tmcmc_joint(obs, n_particles=200, sigma_ll=0.05, output_path=None,
                    mutation='rw', use_sign_prior=False):
    """
    GPU-accelerated joint TMCMC (shared-A, per-patient-b, 65 params).
    Uses jax.vmap over 10 patients (inner) + vmap over particles (outer).
    """
    from tmcmc_nuts_engine import tmcmc_engine

    print(f"  n_sp={N_SP}, n_params={N_PARAMS} (A={N_A_PARAMS}, b={N_B_PARAMS})")
    print(f"  n_patients={N_PATIENTS}, n_particles={n_particles}, mutation={mutation}")
    print(f"  sign_prior={'ON' if use_sign_prior else 'OFF'}")

    log_likelihood = make_log_likelihood_joint_jax(obs, sigma=sigma_ll)
    bounds = _make_prior_bounds()
    log_prior_fn = make_log_prior_jax() if use_sign_prior else None

    # Warm-up JIT compile check
    import time
    t0 = time.time()
    _ = jax.jit(log_likelihood)(jnp.zeros(N_PARAMS, dtype=jnp.float32))
    print(f"  JIT compile: {time.time()-t0:.1f}s")

    result = tmcmc_engine(
        log_likelihood=log_likelihood,
        prior_bounds=bounds,
        mutation=mutation,
        n_particles=n_particles,
        log_prior_fn=log_prior_fn,
        label=f'Dieckow-5sp-joint-{mutation}',
        verbose=True,
    )

    map_theta = np.array(result['theta_MAP'])
    r = rmse_joint(map_theta, obs)
    print(f"  MAP RMSE: {r:.4f}")

    out = {
        'theta_map':    map_theta.tolist(),
        'samples':      np.array(result['samples']).tolist(),
        'rmse':         r,
        'n_stages':     result.get('n_stages', -1),
        'genera':       GENERA_5,
        'patient_order': PATIENT_ORDER,
        'n_A_params':   N_A_PARAMS,
        'n_B_params':   N_B_PARAMS,
        'sign_prior':   use_sign_prior,
    }
    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(out, f, indent=2)
        print(f"  Saved: {output_path}")
    return out


def _init_theta_from_heine():
    """Load Heine DH MAP theta as initial A; set b=1 for all patients."""
    RUNS = Path('/home/nishioka/IKM_Hiwi/Tmcmc202601/data_5species/_runs')
    path = RUNS / 'dh_baseline' / 'theta_MAP.json'
    theta0 = np.zeros(N_PARAMS)
    theta0[N_A_PARAMS:] = 1.0   # b = 1 default

    if path.exists():
        with open(path) as f:
            d = json.load(f)
        raw = np.array(d.get('theta_full', d.get('theta_sub')))
        # Extract upper triangle from Heine layout (same as attractor_analysis.py)
        A = np.zeros((5, 5))
        A[0,0]=raw[0]; A[0,1]=A[1,0]=raw[1]; A[1,1]=raw[2]
        A[2,2]=raw[5]; A[2,3]=A[3,2]=raw[6]; A[3,3]=raw[7]
        A[0,2]=A[2,0]=raw[10]; A[0,3]=A[3,0]=raw[11]
        A[1,2]=A[2,1]=raw[12]; A[1,3]=A[3,1]=raw[13]
        A[4,4]=raw[14]
        A[0,4]=A[4,0]=raw[16]; A[1,4]=A[4,1]=raw[17]
        A[2,4]=A[4,2]=raw[18]; A[3,4]=A[4,3]=raw[19]
        b_heine = np.array([raw[3], raw[4], raw[8], raw[9], raw[15]])
        k = 0
        for r in range(5):
            for c in range(r, 5):
                theta0[k] = A[r, c]; k += 1
        # Use Heine b as starting point for all patients
        for i in range(N_PATIENTS):
            theta0[N_A_PARAMS + i*N_SP: N_A_PARAMS + (i+1)*N_SP] = b_heine
        print("  Initialized A from Heine DH MAP theta")
    return theta0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Dieckow Hamilton ODE fitting (n_sp=5 shared-A, GPU vmap)')
    parser.add_argument('--build-data',   action='store_true', help='Rebuild obs matrix')
    parser.add_argument('--fit',          action='store_true', help='Run joint TMCMC fit')
    parser.add_argument('--info',         action='store_true', help='Print data summary')
    parser.add_argument('--n-particles',  type=int,   default=200)
    parser.add_argument('--sigma',        type=float, default=0.05)
    parser.add_argument('--output',       default=None)
    parser.add_argument('--mutation',     default='rw', choices=['rw', 'hmc', 'nuts'],
                        help='TMCMC mutation kernel (default: rw)')
    parser.add_argument('--sign-prior',   action='store_true',
                        help='Enable Bergey/Dieckow soft sign prior')
    parser.add_argument('--device',       default='auto', choices=['auto', 'gpu', 'cpu'])
    args = parser.parse_args()

    obs = load_or_build_data(force=args.build_data)

    if args.info or (not args.fit and not args.build_data):
        print(f"\nPatients available: {sorted(obs.keys())}")
        print(f"Genera ({N_SP}): {GENERA_5}")
        print(f"Theta layout: A_utri({N_A_PARAMS}) + b_patients({N_B_PARAMS}) = {N_PARAMS} params")
        for p in PATIENT_ORDER:
            if p not in obs:
                print(f"  Patient {p}: no data")
                continue
            m = obs[p]
            weeks_ok = (m.sum(axis=0) > 0).sum()
            print(f"  Patient {p}: {weeks_ok} weeks  "
                  f"So={m[0,0]:.3f} Fn={m[3,0]:.3f} Pg={m[4,0]:.3f} (week1)")
        return

    if args.fit:
        out_dir = Path('/home/nishioka/IKM_Hiwi/nife/results/dieckow_fits')
        out_dir.mkdir(parents=True, exist_ok=True)
        out = args.output or str(out_dir / 'fit_joint_5sp.json')
        run_tmcmc_joint(obs, n_particles=args.n_particles, sigma_ll=args.sigma,
                        output_path=out, mutation=args.mutation,
                        use_sign_prior=args.sign_prior)


if __name__ == '__main__':
    main()
