"""Thesis figure: Neural ODE with metabolic sign-prior constraint.

Reads results/neural_ode_sign/results.json
(generated by scripts/fitting/neural_ode_sign_prior.py).

Run (with TeX Live on PATH):
    PATH=/home/nishioka/texlive/2025/bin/x86_64-linux:$PATH \
        python scripts/figures/generate_fig_neural_ode.py
"""
# [nife-pathshim]
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import json
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

from thesis_style import use, PALETTE, clean_ax
from guild_replicator_dieckow import GUILD_ORDER, GUILD_SHORT, N_G
from loo_cv_kegg_prior import build_net_flow

_here   = Path(__file__).resolve().parents[2]
RES_DIR = _here / 'results' / 'neural_ode_sign'
FIT_FILE = _here / 'results' / 'dieckow_cr' / 'fit_glv_hamilton_kegg_prior.json'
OUT_PDF  = RES_DIR / 'fig_neural_ode_thesis.pdf'

GUILD_LABELS = [GUILD_SHORT.get(g, g) for g in GUILD_ORDER]


def main():
    with open(RES_DIR / 'results.json') as f:
        res = json.load(f)
    with open(FIT_FILE) as f:
        fit_ref = json.load(f)

    A_neural   = np.array(res['A_neural'])
    A_glv      = np.array(fit_ref['A'])
    sa_neural  = res['sign_agree_neural']
    sa_glv     = res['sign_agree_glv']
    rmse_neural = res['rmse_neural']
    rmse_glv    = res.get('rmse_glv', float('nan'))
    corr        = res['A_corr_neural_glv']

    net_flow = build_net_flow()
    sp       = np.sign(net_flow)
    off      = ~np.eye(N_G, dtype=bool)
    prior_mask = (sp != 0)

    figsize = use(width_frac=1.0, aspect=0.38)
    fig, axes = plt.subplots(1, 3, figsize=figsize)

    # ── Panel A: A matrix heatmaps — gLV vs Neural ODE ──
    # Show both side by side in one axes via two imshow with twin axes
    ax = axes[0]
    vmax = max(np.abs(A_neural).max(), np.abs(A_glv).max())

    # Difference matrix
    diff = A_neural - A_glv
    vmax_d = np.abs(diff).max()
    im = ax.imshow(diff, cmap='PuOr', vmin=-vmax_d, vmax=vmax_d, aspect='auto')

    # Mark sign-prior positions
    for i in range(N_G):
        for j in range(N_G):
            if prior_mask[i, j] and i != j:
                agree_n = np.sign(A_neural[i,j]) == sp[i,j]
                agree_g = np.sign(A_glv[i,j])    == sp[i,j]
                if agree_n and not agree_g:
                    ax.plot(j, i, 's', ms=3, color='lime', mec='k', mew=0.4)

    ax.set_xticks(range(N_G))
    ax.set_xticklabels(GUILD_LABELS, rotation=50, ha='right', fontsize=5.5)
    ax.set_yticks(range(N_G))
    ax.set_yticklabels(GUILD_LABELS, fontsize=5.5)
    ax.set_title(r'$\Delta A = A_{\mathrm{neural}} - A_{\mathrm{gLV}}$')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    legend_els = [Line2D([0],[0], marker='s', color='w', markerfacecolor='lime',
                         markeredgecolor='k', markersize=4,
                         label='Neural fixes prior sign')]
    ax.legend(handles=legend_els, fontsize=6, loc='upper right')

    # ── Panel B: A_neural vs A_glv scatter ──
    ax = axes[1]
    colors_pt = []
    for i in range(N_G):
        for j in range(N_G):
            if prior_mask[i, j] and off[i, j]:
                agree_n = np.sign(A_neural[i,j]) == sp[i,j]
                colors_pt.append(PALETTE['prior_on'] if agree_n else PALETTE['dysbiosis'])
            else:
                colors_pt.append(PALETTE['prior_off'])

    ax.scatter(A_glv.flatten(), A_neural.flatten(), s=18, alpha=0.7,
               c=colors_pt, zorder=3)
    lim = max(np.abs(A_glv).max(), np.abs(A_neural).max()) * 1.1
    ax.plot([-lim, lim], [-lim, lim], 'k--', lw=0.7, label='$y=x$')
    ax.set_xlabel(r'$A_{ij}^{\mathrm{gLV}}$')
    ax.set_ylabel(r'$A_{ij}^{\mathrm{neural}}$')
    ax.set_title(r'Pearson $r = %.2f$' % corr)
    legend_els2 = [
        Line2D([0],[0], marker='o', color='w', markerfacecolor=PALETTE['prior_on'],
               markersize=5, label='Prior agree (neural)'),
        Line2D([0],[0], marker='o', color='w', markerfacecolor=PALETTE['dysbiosis'],
               markersize=5, label='Prior disagree (neural)'),
        Line2D([0],[0], ls='--', color='k', label='$y=x$'),
    ]
    ax.legend(handles=legend_els2, fontsize=6)
    clean_ax(ax)

    # ── Panel C: Sign agreement & RMSE comparison ──
    ax = axes[2]
    models   = ['gLV\n(+ sign prior)', 'Neural ODE\n(+ sign prior)']
    sa_vals  = [sa_glv, sa_neural]
    rm_vals  = [rmse_glv, rmse_neural]
    cols     = [PALETTE['prior_off'], PALETTE['health']]
    x        = np.arange(2)

    ax2 = ax.twinx()
    bars1 = ax.bar(x - 0.18, sa_vals,  0.32, color=cols, alpha=0.85, label='Sign agree.')
    bars2 = ax2.bar(x + 0.18, rm_vals, 0.32, color=cols, alpha=0.50,
                    hatch='//', edgecolor='k', linewidth=0.5, label='RMSE')

    ax.axhline(0.5, color='k', lw=0.7, ls='--', label='Chance')
    ax.set_ylim(0, 1.1)
    ax2.set_ylim(0, max(rm_vals) * 2.5)
    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=7)
    ax.set_ylabel('Sign agreement with metabolic prior')
    ax2.set_ylabel('RMSE', color='grey')
    ax2.tick_params(axis='y', colors='grey')
    ax.set_title('Model comparison')

    for bar, v in zip(bars1, sa_vals):
        ax.text(bar.get_x() + bar.get_width()/2, v + 0.01, f'{v:.2f}',
                ha='center', va='bottom', fontsize=7)
    for bar, v in zip(bars2, rm_vals):
        if not np.isnan(v):
            ax2.text(bar.get_x() + bar.get_width()/2, v + 0.001, f'{v:.3f}',
                     ha='center', va='bottom', fontsize=6, color='grey')

    lines1, labels1 = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines1 + lines2, labels1 + labels2, fontsize=6, loc='upper left')
    ax.spines['top'].set_visible(False)

    fig.tight_layout()
    fig.savefig(OUT_PDF)
    print(f'Saved: {OUT_PDF}')


if __name__ == '__main__':
    main()
