"""Thesis figure: early attractor predictor for oral biofilm dynamics.

Reads pre-computed results from results/attractor_predictor/results.json
(generated by scripts/analysis/early_attractor_predictor.py) and the raw
phi arrays, then produces a publication-quality 3-panel figure.

Run (with TeX Live on PATH):
    PATH=/home/nishioka/texlive/2025/bin/x86_64-linux:$PATH \
        python scripts/figures/generate_fig_attractor_predictor.py
"""
# [nife-pathshim]
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import json
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.decomposition import PCA
from scipy.integrate import solve_ivp

from thesis_style import use, PALETTE, clean_ax
from guild_replicator_dieckow import GUILD_ORDER, GUILD_SHORT, N_G

_here   = Path(__file__).resolve().parents[2]
RES_DIR = _here / 'results' / 'attractor_predictor'
PHI_NPY = _here / 'results' / 'dieckow_otu' / 'phi_guild.npy'
FIT_FILE = _here / 'results' / 'dieckow_cr' / 'fit_glv_hamilton_kegg_prior.json'
OUT_PDF = RES_DIR / 'fig_attractor_predictor_thesis.pdf'

GUILD_LABELS = [GUILD_SHORT.get(g, g) for g in GUILD_ORDER]

ATTRACTOR_COLORS = ['#2196A6', '#D95F02', '#7B3294']   # teal / orange / purple
ATTRACTOR_NAMES  = ['Attractor A', 'Attractor B', 'Attractor C']


def replicator_rhs(t, phi, b, A):
    f = b + A @ phi
    return phi * (f - phi @ f)


def integrate_to(phi0, b, A, t_end, t_eval=None):
    sol = solve_ivp(replicator_rhs, [0, t_end], phi0, args=(b, A),
                    method='RK45', rtol=1e-7, atol=1e-9, t_eval=t_eval)
    y = sol.y
    norms = np.where(y.sum(axis=0) < 1e-12, 1.0, y.sum(axis=0))
    return y / norms


def main():
    # ── Load results ──
    with open(RES_DIR / 'results.json') as f:
        res = json.load(f)
    k         = res['k']
    sil       = res['silhouette']
    loo_acc   = res['loo_acc']
    real_acc  = res['real_acc']
    centers   = np.array(res['attractor_centers'])
    real_pred = np.array(res['real_pred'])
    real_truth = np.array(res['real_truth'])

    feat_imp  = res['feature_importance']
    feat_names = list(feat_imp.keys())
    feat_vals  = np.array(list(feat_imp.values()))

    phi_dieckow = np.load(PHI_NPY)

    # Re-simulate for PCA (lightweight, 400 pts)
    with open(FIT_FILE) as f:
        fit = json.load(f)
    A     = np.array(fit['A'])
    b_mean = np.array(fit['b_all']).mean(axis=0)

    rng = np.random.default_rng(0)
    n_sim = 400
    phi_final = np.zeros((n_sim, N_G))
    labels_sim = []
    from scipy.spatial.distance import cdist
    for i in range(n_sim):
        alpha = rng.exponential(1.0, N_G) + 0.01
        phi0  = alpha / alpha.sum()
        traj  = integrate_to(phi0, b_mean, A, 150.0, t_eval=[0.0, 150.0])
        phi_f = traj[:, 1]
        phi_final[i] = phi_f
    dists  = cdist(phi_final, centers)
    labels_sim = dists.argmin(axis=1)

    # PCA
    pca = PCA(n_components=2)
    pcs = pca.fit_transform(phi_final)
    pcs_real = pca.transform(phi_dieckow[:, 2, :])

    # ── Figure ──
    figsize = use(width_frac=1.0, aspect=0.38)
    fig, axes = plt.subplots(1, 3, figsize=figsize)

    # ── Panel A: PCA ──
    ax = axes[0]
    for c in range(k):
        mask = labels_sim == c
        ax.scatter(pcs[mask, 0], pcs[mask, 1], s=4, alpha=0.25,
                   color=ATTRACTOR_COLORS[c], rasterized=True)
    for i in range(len(phi_dieckow)):
        ax.scatter(pcs_real[i, 0], pcs_real[i, 1], s=55,
                   color=ATTRACTOR_COLORS[real_truth[i]],
                   edgecolors='k', linewidths=0.7, zorder=5)
    ax.set_xlabel(r'PC 1 (%.0f\%%)'  % (pca.explained_variance_ratio_[0]*100))
    ax.set_ylabel(r'PC 2 (%.0f\%%)' % (pca.explained_variance_ratio_[1]*100))
    ax.set_title(r'Converged states (PCA, $k=%d$)' % k)
    legend_handles = [
        mpatches.Patch(color=ATTRACTOR_COLORS[c], label=ATTRACTOR_NAMES[c])
        for c in range(k)
    ]
    legend_handles.append(
        plt.Line2D([0], [0], marker='o', color='w', markerfacecolor='grey',
                   markeredgecolor='k', markersize=5, label='Real patient')
    )
    ax.legend(handles=legend_handles, fontsize=6, loc='best')
    clean_ax(ax)

    # ── Panel B: Attractor guild composition ──
    ax = axes[1]
    x = np.arange(N_G)
    bar_w = 0.75 / k
    for c in range(k):
        ax.bar(x + c * bar_w, centers[c], width=bar_w,
               color=ATTRACTOR_COLORS[c], label=ATTRACTOR_NAMES[c], alpha=0.85)
    ax.set_xticks(x + bar_w * (k - 1) / 2)
    ax.set_xticklabels(GUILD_LABELS, rotation=50, ha='right', fontsize=6)
    ax.set_ylabel('Mean guild composition')
    ax.set_title('Attractor centroids')
    ax.legend(fontsize=6)
    clean_ax(ax)

    # ── Panel C: Feature importance ──
    ax = axes[2]
    order = np.argsort(feat_vals)[::-1][:10]
    short_names = []
    for fn in [feat_names[o] for o in order]:
        tp, g = fn.split('_', 1)
        short_names.append(r'$\phi_{%s}^{(%s)}$' % (g[:4], tp))
    ax.barh(range(10), feat_vals[order][::-1], color='steelblue', alpha=0.82)
    ax.set_yticks(range(10))
    ax.set_yticklabels(short_names[::-1], fontsize=6)
    ax.set_xlabel('Feature importance (RF)')
    ax.set_title(r'Early predictors (LOO acc.\ $=%.2f$)' % loo_acc)
    clean_ax(ax)

    fig.tight_layout()
    fig.savefig(OUT_PDF)
    print(f'Saved: {OUT_PDF}')


if __name__ == '__main__':
    main()
