"""Thesis figure: symbolic regression — what predicts A_ij?

Reads results/symbolic_regression/results.json
(generated by scripts/analysis/symbolic_regression_A.py).

Run (with TeX Live on PATH):
    PATH=/home/nishioka/texlive/2025/bin/x86_64-linux:$PATH \
        python scripts/figures/generate_fig_symbolic_regression_A.py
"""
# [nife-pathshim]
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import json
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

from thesis_style import use, PALETTE, clean_ax
from guild_replicator_dieckow import GUILD_ORDER, GUILD_SHORT, N_G

_here   = Path(__file__).resolve().parents[2]
RES_DIR = _here / 'results' / 'symbolic_regression'
OUT_PDF = RES_DIR / 'fig_symbolic_regression_thesis.pdf'

GUILD_LABELS = [GUILD_SHORT.get(g, g) for g in GUILD_ORDER]


def main():
    with open(RES_DIR / 'results.json') as f:
        res = json.load(f)

    A        = np.array(res['A'])
    net_flow = np.array(res['net_flow'])
    sa       = res['sign_agreement_off_diag']
    loo_r2   = res['poly_regression']['loo_r2']
    full_r2  = res['poly_regression']['full_r2']
    top_terms = res['poly_regression']['top_terms']

    off = ~np.eye(N_G, dtype=bool)
    A_off  = A[off]
    nf_off = net_flow[off]

    # sign-agreement colour per pair
    sp      = np.sign(net_flow)
    agree   = np.sign(A) == sp          # (N_G, N_G)
    # mask: only pairs with non-zero prior
    prior_mask = (sp != 0)

    figsize = use(width_frac=1.0, aspect=0.38)
    fig, axes = plt.subplots(1, 3, figsize=figsize)

    # ── Panel A: A_ij vs net_flow scatter ──
    ax = axes[0]
    colors_pt = []
    for i in range(N_G):
        for j in range(N_G):
            if i == j:
                colors_pt.append('grey')
            elif prior_mask[i, j]:
                colors_pt.append(PALETTE['prior_on'] if agree[i, j] else PALETTE['dysbiosis'])
            else:
                colors_pt.append(PALETTE['prior_off'])

    ax.scatter(net_flow.flatten(), A.flatten(), s=20, alpha=0.75,
               c=colors_pt, zorder=3)
    ax.axhline(0, color='k', lw=0.5, ls='--')
    ax.axvline(0, color='k', lw=0.5, ls='--')
    ax.set_xlabel(r'Metabolic flow $F_{ij}$ (Szafranski)')
    ax.set_ylabel(r'Fitted interaction $A_{ij}$')
    ax.set_title(r'Sign agreement $= %.2f$' % sa)
    from matplotlib.lines import Line2D
    legend_els = [
        Line2D([0],[0], marker='o', color='w', markerfacecolor=PALETTE['prior_on'],
               markersize=5, label='Prior agree'),
        Line2D([0],[0], marker='o', color='w', markerfacecolor=PALETTE['dysbiosis'],
               markersize=5, label='Prior disagree'),
        Line2D([0],[0], marker='o', color='w', markerfacecolor=PALETTE['prior_off'],
               markersize=5, label='No prior'),
    ]
    ax.legend(handles=legend_els, fontsize=6)
    clean_ax(ax)

    # ── Panel B: Top regression terms ──
    ax = axes[1]
    # Use readable labels: map x0..x9 to feature names
    feat_map = {
        'x0': r'$F_{ij}$', 'x1': r'$|F_{ij}|$', 'x2': r'$F_{ji}$',
        'x3': r'oxy$_i$',  'x4': r'gram$_i$',    'x5': r'oxy$_j$',
        'x6': r'gram$_j$', 'x7': r'oxy$_i$oxy$_j$',
        'x8': r'gram$_i$gram$_j$', 'x9': r'self',
    }
    def readable(term):
        import re
        parts = re.split(r'(\s+)', term)
        out = []
        for p in parts:
            base = re.sub(r'\^\d+', '', p)
            exp  = re.findall(r'\^(\d+)', p)
            label = feat_map.get(base, p)
            if exp:
                label = label + r'$^{%s}$' % exp[0]
            out.append(label)
        return ''.join(out)

    names  = [readable(t[0]) for t in top_terms[:8]]
    coefs  = [t[1] for t in top_terms[:8]]
    colors = [PALETTE['prior_on'] if c > 0 else PALETTE['dysbiosis'] for c in coefs]
    y_pos  = np.arange(len(names))
    ax.barh(y_pos, np.abs(coefs), color=colors, alpha=0.82)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(names, fontsize=6)
    ax.set_xlabel(r'$|$coefficient$|$')
    ax.set_title(r'Top predictors (LOO $R^2=%.2f$)' % loo_r2)
    clean_ax(ax)

    # ── Panel C: A matrix heatmap ──
    ax = axes[2]
    vmax = np.abs(A).max()
    im = ax.imshow(A, cmap='RdBu_r', vmin=-vmax, vmax=vmax, aspect='auto')

    for i in range(N_G):
        for j in range(N_G):
            if prior_mask[i, j] and i != j:
                marker = r'$+$' if sp[i, j] > 0 else r'$\times$'
                col    = 'lime' if agree[i, j] else 'red'
                ax.text(j, i, marker, ha='center', va='center',
                        fontsize=5, color=col, fontweight='bold')

    ax.set_xticks(range(N_G))
    ax.set_xticklabels(GUILD_LABELS, rotation=50, ha='right', fontsize=5.5)
    ax.set_yticks(range(N_G))
    ax.set_yticklabels(GUILD_LABELS, fontsize=5.5)
    ax.set_title(r'$A$ matrix (marker = prior sign)')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04,
                 label=r'$A_{ij}$')

    fig.tight_layout()
    fig.savefig(OUT_PDF)
    print(f'Saved: {OUT_PDF}')


if __name__ == '__main__':
    main()
