#!/usr/bin/env python3
"""
augment_diffusion.py — ③ DDPM-based data augmentation for ML baselines.

Trains an *unconditional* DDPM on all 10 patients' phi trajectories
(30 data points in 30-dim space: 3 weeks × 10 guilds), generates N_aug
synthetic trajectories, and reruns Ridge/RF LOO-CV with augmented training
data to test whether diffusion augmentation bridges the RMSE gap to gLV.

Key question: does synthetic data generated by a DDPM (trained on n=30)
help data-hungry models like Ridge/RF approach gLV accuracy?

Architecture:
  Unconditional DDPM on 30-dim trajectory vectors (phi_W1, phi_W2, phi_W3)
  Score net: MLP(x_noisy, t_embed) -> noise_pred
  T = 300 steps, cosine schedule

Usage (repo root):
  python scripts/analysis/augment_diffusion.py [--n-aug 200] [--epochs 3000]

Output:
  results/benchmark_baselines/augmented_rmse_table.json
"""
import sys as _sys, pathlib as _pathlib  # noqa: E402  [nife-pathshim]
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[2]))

import argparse, json
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

_here = Path(__file__).resolve().parents[2]
PHI_NPY = _here / 'results' / 'dieckow_otu' / 'phi_guild.npy'
OUT_DIR = _here / 'results' / 'benchmark_baselines'
OUT_DIR.mkdir(exist_ok=True)

N_G      = 10
N_FOLDS  = 10
DIM_TRAJ = N_G * 3   # flatten (3, 10) trajectory
PATIENTS = list('ABCDEFGHKL')


# ── Cosine schedule ───────────────────────────────────────────────────────────

def cosine_schedule(T, s=0.008):
    t = torch.arange(T + 1, dtype=torch.float32)
    f = torch.cos(((t / T + s) / (1 + s)) * (torch.pi / 2)) ** 2
    ac = f / f[0]
    betas = torch.clamp(1 - ac[1:] / ac[:-1], 1e-4, 0.9999)
    return betas, ac[1:]


# ── Unconditional score net ───────────────────────────────────────────────────

class UncondScoreNet(nn.Module):
    def __init__(self, dim=DIM_TRAJ, hidden=128, t_dim=32):
        super().__init__()
        self.t_emb = nn.Sequential(
            nn.Linear(1, t_dim), nn.SiLU(), nn.Linear(t_dim, t_dim),
        )
        self.net = nn.Sequential(
            nn.Linear(dim + t_dim, hidden), nn.SiLU(),
            nn.Linear(hidden, hidden), nn.SiLU(),
            nn.Linear(hidden, hidden), nn.SiLU(),
            nn.Linear(hidden, dim),
        )

    def forward(self, x, t_norm):
        te = self.t_emb(t_norm.unsqueeze(-1))
        return self.net(torch.cat([x, te], dim=-1))


# ── Unconditional DDPM ────────────────────────────────────────────────────────

class UncondDDPM:
    def __init__(self, T=300, hidden=128, device='cpu'):
        self.T      = T
        self.device = device
        self.net    = UncondScoreNet(hidden=hidden).to(device)
        betas, acp  = cosine_schedule(T)
        self.betas   = betas.to(device)
        self.acp     = acp.to(device)
        self.sqrt_ac = torch.sqrt(self.acp)
        self.sqrt_1m = torch.sqrt(1 - self.acp)

    def train_model(self, X, epochs=3000, lr=3e-4):
        """X: (N, DIM_TRAJ) normalised trajectory vectors."""
        Xt  = torch.tensor(X, dtype=torch.float32).to(self.device)
        N   = Xt.shape[0]
        opt = optim.Adam(self.net.parameters(), lr=lr)
        sch = optim.lr_scheduler.CosineAnnealingLR(opt, epochs)
        self.net.train()
        for ep in range(epochs):
            idx  = torch.randint(0, N, (min(N, 16),))
            x0   = Xt[idx]
            t    = torch.randint(0, self.T, (len(idx),)).to(self.device)
            eps  = torch.randn_like(x0)
            xt   = self.sqrt_ac[t, None] * x0 + self.sqrt_1m[t, None] * eps
            tn   = (t.float() / self.T)
            loss = nn.functional.mse_loss(self.net(xt, tn), eps)
            opt.zero_grad(); loss.backward(); opt.step(); sch.step()

    @torch.no_grad()
    def sample_batch(self, n, scaler):
        """Generate n synthetic trajectories, reverse-normalise, project to simplex."""
        self.net.eval()
        xt = torch.randn(n, DIM_TRAJ).to(self.device)
        for t_idx in reversed(range(self.T)):
            tn   = torch.full((n,), t_idx / self.T).to(self.device)
            eps_pred = self.net(xt, tn)
            ac_t  = self.acp[t_idx]
            ac_tm1 = self.acp[t_idx - 1] if t_idx > 0 else torch.tensor(1.0).to(self.device)
            x0_pred = (xt - torch.sqrt(1 - ac_t) * eps_pred) / torch.sqrt(ac_t)
            xt = torch.sqrt(ac_tm1) * x0_pred + torch.sqrt(1 - ac_tm1) * eps_pred
        raw = xt.cpu().numpy()
        raw = scaler.inverse_transform(raw)  # (n, 30)
        # Project each week to simplex
        trajs = raw.reshape(n, 3, N_G)
        trajs = np.clip(trajs, 0, None)
        sums  = trajs.sum(axis=-1, keepdims=True)
        sums  = np.where(sums < 1e-12, 1.0, sums)
        return trajs / sums                  # (n, 3, 10)


# ── LOO helpers ───────────────────────────────────────────────────────────────

def _loo_rmse_model(predict_fn, phi_all, hold):
    tr_idx = [i for i in range(N_FOLDS) if i != hold]
    phi_tr  = phi_all[tr_idx]
    X_tr    = phi_tr[:, :-1, :].reshape(-1, N_G)
    y_tr    = phi_tr[:, 1:,  :].reshape(-1, N_G)
    phi_ho  = phi_all[hold]
    pred_W2 = predict_fn(X_tr, y_tr, phi_ho[0])
    pred_W3 = predict_fn(X_tr, y_tr, pred_W2)
    return float(np.sqrt((np.mean((pred_W2 - phi_ho[1])**2) +
                          np.mean((pred_W3 - phi_ho[2])**2)) / 2))


def _make_ridge():
    def predict(X_tr, y_tr, phi):
        sc = StandardScaler()
        Xs = sc.fit_transform(X_tr)
        m  = Ridge(alpha=1.0).fit(Xs, y_tr)
        p  = m.predict(sc.transform(phi.reshape(1, -1)))[0]
        p  = np.clip(p, 0, None); s = p.sum()
        return p / s if s > 1e-12 else phi.copy()
    return predict


def _make_rf():
    def predict(X_tr, y_tr, phi):
        m = RandomForestRegressor(n_estimators=200, random_state=42)
        m.fit(X_tr, y_tr)
        p = m.predict(phi.reshape(1, -1))[0]
        p = np.clip(p, 0, None); s = p.sum()
        return p / s if s > 1e-12 else phi.copy()
    return predict


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n-aug',  type=int, default=200,
                        help='synthetic trajectories generated per fold')
    parser.add_argument('--epochs', type=int, default=3000)
    parser.add_argument('--T',      type=int, default=300, help='diffusion steps')
    parser.add_argument('--seed',   type=int, default=42)
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    phi_all = np.load(PHI_NPY)   # (10,3,10)
    print(f'phi: {phi_all.shape}  n_aug={args.n_aug}  epochs={args.epochs}')

    results = {}
    for method_name, pred_fn in [('ridge_aug', _make_ridge()), ('rf_aug', _make_rf())]:
        rmses = []
        for fold in range(N_FOLDS):
            tr_idx = [i for i in range(N_FOLDS) if i != fold]
            phi_tr = phi_all[tr_idx]          # (9,3,10)

            # Train unconditional DDPM on 9 training patients
            X_flat = phi_tr.reshape(-1, DIM_TRAJ).astype(np.float32)  # (9, 30)
            scaler = StandardScaler()
            X_norm = scaler.fit_transform(X_flat)

            model = UncondDDPM(T=args.T)
            model.train_model(X_norm, epochs=args.epochs)

            # Generate synthetic trajectories
            aug_trajs = model.sample_batch(args.n_aug, scaler)    # (n_aug,3,10)

            # Augment training set
            phi_aug = np.concatenate([phi_tr, aug_trajs], axis=0)  # (9+n_aug,3,10)

            X_tr_aug = phi_aug[:, :-1, :].reshape(-1, N_G)
            y_tr_aug = phi_aug[:, 1:,  :].reshape(-1, N_G)

            phi_ho = phi_all[fold]

            def predict_aug(X_tr_in, y_tr_in, phi_in):
                return pred_fn(X_tr_aug, y_tr_aug, phi_in)

            pred_W2 = predict_aug(X_tr_aug, y_tr_aug, phi_ho[0])
            pred_W3 = predict_aug(X_tr_aug, y_tr_aug, pred_W2)
            r = float(np.sqrt((np.mean((pred_W2 - phi_ho[1])**2) +
                               np.mean((pred_W3 - phi_ho[2])**2)) / 2))
            rmses.append(r)
            print(f'  {method_name}  fold {fold}  RMSE={r:.4f}')

        results[method_name] = {
            'mean_rmse': float(np.mean(rmses)),
            'std_rmse':  float(np.std(rmses)),
            'per_fold':  rmses,
            'n_aug':     args.n_aug,
        }
        print(f'  {method_name}  MEAN={results[method_name]["mean_rmse"]:.4f}  '
              f'STD={results[method_name]["std_rmse"]:.4f}\n')

    # Also compute non-augmented for direct comparison
    print('--- non-augmented baselines for comparison ---')
    for method_name, pred_fn in [('ridge_no_aug', _make_ridge()), ('rf_no_aug', _make_rf())]:
        rmses = [_loo_rmse_model(pred_fn, phi_all, fold) for fold in range(N_FOLDS)]
        results[method_name] = {'mean_rmse': float(np.mean(rmses)),
                                'std_rmse':  float(np.std(rmses)),
                                'per_fold':  rmses}
        print(f'  {method_name}  MEAN={results[method_name]["mean_rmse"]:.4f}')

    # Compare augmented vs non-augmented
    print('\n=== Augmentation effect ===')
    for base in ['ridge', 'rf']:
        orig = results[f'{base}_no_aug']['mean_rmse']
        aug  = results[f'{base}_aug' ]['mean_rmse']
        delta = aug - orig
        sign  = 'BETTER' if delta < 0 else 'WORSE'
        print(f'  {base}: {orig:.4f} → {aug:.4f}  Δ={delta:+.4f}  ({sign})')
    print(f'  (gLV no-prior reference: 0.0509)')

    out_path = OUT_DIR / 'augmented_rmse_table.json'
    json.dump(results, open(out_path, 'w'), indent=2)
    print(f'\nSaved: {out_path}')


if __name__ == '__main__':
    main()
